#!/usr/bin/env python3

import os
import sys


HERE = os.path.dirname(os.path.abspath(__file__))
if HERE not in sys.path:
    sys.path.insert(0, HERE)

from kb_ai.cli import main


if __name__ == "__main__":
    raise SystemExit(main())
